### PR TITLE
Kmurchison fixes

### PR DESCRIPTION
**Pull request by ksmurchison**
Allen,

These are all of my substantial fixes to vzic to make it output (pure) VTIMEZONEs, that when expanded will produce the same transitions as zdump will on zic-compiled timezones

### CODE REVIEW

**Comment by ksmurchison** [comment]
The only diff that I left out was one that can include the TZ description and geo coords pulled from zone.tab

**Comment by ksmurchison** [comment]
Note that these fixes will output RRULEs whenever possible, thus producing smaller files.  I don't think RRULE:FREQ=YEARLY expansion is all that expensive anymore, especially on current hardware

**Comment by winterz** [comment]
merged and I updated tzdata.
I don't know if these warnings/errors from vzic are trouble or not.

$ ./vzic
WARNING: Asia/Shanghai: Modifying RRULE to be compatible with Outlook (day >= 10, month = 4)
ERROR: Asia/Shanghai: Couldn't modify RRULE to be compatible with Outlook (day >= 10, month = 4)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Shanghai: Modifying RRULE to be compatible with Outlook (day >= 11, month = 9)
ERROR: Asia/Shanghai: Couldn't modify RRULE to be compatible with Outlook (day >= 11, month = 9)
 ===> FAILING BACK TO PURE MODE THEN
Skipping DAYLIGHT change
Skipping DAYLIGHT change
WARNING: Asia/Shanghai: Outputting BYDAY=1SU instead of BYMONTHDAY=1-7 for Outlook compatability
Skipping DAYLIGHT change
WARNING: Asia/Macau: Modifying RRULE to be compatible with Outlook (day >= 16, month = 10)
ERROR: Asia/Macau: Couldn't modify RRULE to be compatible with Outlook (day >= 16, month = 10)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Macau: Modifying RRULE to be compatible with Outlook (day >= 16, month = 4)
ERROR: Asia/Macau: Couldn't modify RRULE to be compatible with Outlook (day >= 16, month = 4)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Tehran: Outputting BYDAY=3SU instead of BYMONTHDAY=15-21 for Outlook compatability
WARNING: Asia/Tehran: Outputting BYDAY=3SU instead of BYMONTHDAY=15-21 for Outlook compatability
ERROR: Asia/Tehran: Couldn't output RRULE (day=22) compatible with Outlook

**Comment by winterz** [comment]
merged and I updated tzdata.
I don't know if these warnings/errors from vzic are trouble or not.

$ ./vzic
WARNING: Asia/Shanghai: Modifying RRULE to be compatible with Outlook (day >= 10, month = 4)
ERROR: Asia/Shanghai: Couldn't modify RRULE to be compatible with Outlook (day >= 10, month = 4)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Shanghai: Modifying RRULE to be compatible with Outlook (day >= 11, month = 9)
ERROR: Asia/Shanghai: Couldn't modify RRULE to be compatible with Outlook (day >= 11, month = 9)
 ===> FAILING BACK TO PURE MODE THEN
Skipping DAYLIGHT change
Skipping DAYLIGHT change
WARNING: Asia/Shanghai: Outputting BYDAY=1SU instead of BYMONTHDAY=1-7 for Outlook compatability
Skipping DAYLIGHT change
WARNING: Asia/Macau: Modifying RRULE to be compatible with Outlook (day >= 16, month = 10)
ERROR: Asia/Macau: Couldn't modify RRULE to be compatible with Outlook (day >= 16, month = 10)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Macau: Modifying RRULE to be compatible with Outlook (day >= 16, month = 4)
ERROR: Asia/Macau: Couldn't modify RRULE to be compatible with Outlook (day >= 16, month = 4)
 ===> FAILING BACK TO PURE MODE THEN
WARNING: Asia/Tehran: Outputting BYDAY=3SU instead of BYMONTHDAY=15-21 for Outlook compatability
WARNING: Asia/Tehran: Outputting BYDAY=3SU instead of BYMONTHDAY=15-21 for Outlook compatability
ERROR: Asia/Tehran: Couldn't output RRULE (day=22) compatible with Outlook

**Comment by winterz** [comment]
symbolic links aren't a good thing on Windows.
maybe copy the file instead of symlinking it?

**Comment by ksmurchison** [comment]
Do whatever you think is the right thing.  As far as I'm concerned, I'm sick of all of the special crap that vzic has to do to make VTIMEZONEs that play nice with broken MS code.

**Comment by ksmurchison** [comment]
FWIW, I talked to developer of Apple CalendarServer who has his own tool for converting tzdata into VTIMEZONEs and he doesn't do anything special for Outlook or any other product, so maybe we can finally include --pure VTIMEZONEs in libical.

**Comment by winterz** [comment]
I think we're ok to do that. if you are willing to do the necessary work in vzic?

**Pull request merged**
