### PR TITLE
vzic-merge.pl: Several fixes and improvements

### PR DESCRIPTION
**Pull request by minichma**
These are some fixes and improvements of vzic-merge.pl, including:
* properly deal with line-endings
* ignore LAST-MODIFIED when comparing
* delete files for time zones that have been removed from tzdata
* handle symlinks

### CODE REVIEW

**Comment by winterz** [comment]
@minichma  Wow, I'm sorry.  somehow this one got lost.
I'll try to get to this soon.

**Comment by winterz** [comment]
could you fix the conflicts?

**Comment by minichma** [comment]
> could you fix the conflicts?

Sure, fixed it. Was just about some white space.

**Comment by winterz** [comment]
sorry. I  made a new conflict by reformatting with perltidy. please try again, this time with the new .perltidyrc
run `pre-commit install` first

**Comment by minichma** [comment]
No problem, good to have some linter here. Couldn't test everything in detail but it seems that only whitespace changed, so I'd expect everything to work as expected. Don't remember all the details. Just noted, the oldest commit is back from 2019 😆

**Pull request merged**
